[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
snake_game = "CBY3RWGHQJUjK9GBPnV5bzEPjqCZBbnjnLqBwCfCEi6y"

[programs.localnet]
snake_game = "CBY3RWGHQJUjK9GBPnV5bzEPjqCZBbnjnLqBwCfCEi6y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
